name: job-watcher

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes (best effort)
  workflow_dispatch:

permissions:
  contents: write  # allow committing state/seen.json

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run watcher
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          python src/main.py

      - name: Commit state (if changed)
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git add state/seen.json
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore: update state [skip ci]"
            git push
          fi
